### ISSUE TITLE
Invalid encoding error

### ISSUE THREAD

**Issue by IcanDivideBy0** [lo48576/fbxcel#1]
Hello,
I'm trying to parse some FBX files and getting the following error:
```
FBX version: 7.4
Failed to parse FBX file, Data error: Invalid node name encoding: FromUtf8Error { bytes: [105, 110, 97, 114, 121, 32, 32, 0, 26, 0, 232, 28, 0, 0, 98, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 70, 66, 88, 72, 101, 97, 100, 101, 114, 69, 120, 116, 101, 110, 115, 105, 111, 110, 92, 0, 0, 0, 1, 0, 0, 0, 5, 0, 0, 0, 16, 70, 66, 88, 72, 101, 97, 100, 101], error: Utf8Error { valid_up_to: 10, error_len: Some(1) } }
```
I'm using the (almost) exact same code as the example, with FBX files generated by Blender2.8.
Only noticeable difference is that I use the `from_reader` function cause I'm in a web-assembly context, so I can't use any `io::*`.

Tested with 2 files, both of them load properly in other softwares (not only Blender).

I'd be happy to contribute if you have a clue that can point me to the right direction :)

**Comment by IcanDivideBy0** [comment]
Trying to parse this buffer as utf8 up to the 10th index gives some more context, start of the buffer contains: `inary  `

**Comment by lo48576** [comment]
Hello.
Thank you for reporting the issue.

The data reported, `"inary  \x00\x1a\x00\xe8\x1c\x00\x00"`, is a part of FBX magic binary (`Kaydara FBX BInary  \x00...`, cf. <https://github.com/lo48576/fbxcel/blob/v0.2.0/src/low/fbx_header.rs#L53> and <https://github.com/lo48576/fbxcel/blob/v0.2.0/src/low/fbx_header.rs#L97>).
"inary..." is `fbx_magic[13..]`, so I think this 13 bytes were tried to read as FBX node header.

I think the parser is reading wrong place (beginning of the file!), on the assumption that the FBX data is not broken.
(For example, the parser reads the FBX header, and cursor position is not updated, then the parser expects node but reads the beginning of the file again.)

Could you try the code on native environment, not in WASM environment, if possible?
Or, could you paste the example code that can reproduce the problem?
I think there are I/O-related issues.

**Comment by IcanDivideBy0** [comment]
Thanks for your quick answer,
Here is a repository that can reproduce the issue: https://github.com/IcanDivideBy0/fbx-parser-bug

The `model.fbx` file works fine when using the example code as is.
But being in a webassembly context, i can only achieve to get a `&[u8]` as a `io::Read` implementor.
That's why i convert the file reader to a u8 slice

```rs
    let mut buffer: Vec<u8> = Vec::new();
    file.read_to_end(&mut buffer).expect("Cannot create file buffer");
    let buffer: &[u8] = buffer.as_mut_slice();
```
Then I use this buffer to feed the `read_fbx_header` and `from_reader` methods.

PS: I'm kinda new to rust, maybe I missed something obvious...

**Comment by lo48576** [comment]
Ok, confirmed.

This is due to `&[u8]` implementing `io::Read` but not keep the cursor position.
You can do the below:

```rust
    // CHANGED: `let mut buffer` instead of `let buffer`.
    // Additionally, `buffer.as_slice()` is enough here (`as_mut_slice()` is overkill).
    let mut buffer: &[u8] = buffer.as_slice(); // CHANGED: `mut buffer`

    // CHANGED: `&mut buffer` instead of `buffer`
    let header =
        fbxcel::low::FbxHeader::read_fbx_header(&mut buffer).expect("Failed to load FBX header");

    println!(
        "FBX version: {}.{}",
        header.version().major(),
        header.version().minor()
    );

    let parser_version = header.parser_version().expect("Unsupported FBX version");

    match parser_version {
        pull_parser::ParserVersion::V7400 => {
            // CHANGED: `&mut buffer` instead of `buffer`.
            let mut parser = pull_parser::v7400::from_reader(header, &mut buffer)
                .expect("Should never fail: Unsupported FBX verison");
```

`buf: &[u8]` implements `std::io::Read`, but it is immutable, and it doesn't keep cursor position after read operation.
To update cursor position, the buffer should be mutable, so `let mut buf: &[u8] = ...` is appropriate.

Note that, `let buf: &mut [u8] = ...` means "`buf` itself is immutable, but the binary data in range pointed by `buf` is mutable," and, `let mut buf: &[u8] = ...` means "`buf` itself is mutable and the range can be shrinked, but the binary data itself is immutable".

I wrote small example to show read operation difference between immutable `&[u8]` and mutable `&[u8]`: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4e53f1310202c07a0d3dff88c7a7f22c>.

**Comment by IcanDivideBy0** [comment]
Thanks ! working perfectly. You saved my day =)
