### ISSUE TITLE
hello, does it able to rename SMPL fbx model and save it?

### ISSUE THREAD

**Issue by lucasjinreal** [lo48576/fbxcel#9]
Hi, this lib looks like only one active fbx parse lib in rust, however, does there demos on how can I rename all bone names inside a fbx and save it without change anything else?

Meanwhile it would be better to retarget the animations as well

**Comment by lo48576** [comment]
There are two ways to achieve that, in tree modification style and in streaming style.
The former consumes more memory at once, but it enables you to edit nodes in arbitrary order and also lets you read other nodes before editing.
The latter uses less memory at once and supports streaming (non-seekable) input, so maybe more performant but read/write orders are restricted (i.e. events are read in some order, and you should emit events in similar order to keep the output FBX valid).

(I'm not familiar to data structure of animations in FBX, but I guess you may know what nodes and what attributes to edit?
If not, <https://github.com/lo48576/fbx_objects_depviz> or <https://github.com/lo48576/fbx-tree-view> can be useful to inspect the FBX objects structure.)

## Tree modificiation style

1. Load the FBX data into [`fbxcel::tree::v7400::Tree`](https://docs.rs/fbxcel/0.9.0/fbxcel/tree/v7400/struct.Tree.html)
    * See [`fbxcel::tree::any::AnyTree`](https://docs.rs/fbxcel/0.9.0/fbxcel/tree/any/enum.AnyTree.html).
2. Traverse nodes by [`fbxcel::tree::v7400::NodeId::traverse_depth_first()`](https://docs.rs/fbxcel/0.9.0/fbxcel/tree/v7400/struct.NodeId.html#method.traverse_depth_first)
3. If the node you visit is the node you want to change, use [`fbxcel::tree::v7400::Tree::get_attribute_mut()`](https://docs.rs/fbxcel/0.9.0/fbxcel/tree/v7400/struct.Tree.html#method.get_attribute_mut) or similar attributes-manipulation methods.
4. Once all modification is done, write the fbx file with [`fbxcel::writer::v7400::binary::Writer::write_tree()`](https://docs.rs/fbxcel/0.9.0/fbxcel/writer/v7400/binary/struct.Writer.html#method.write_tree) and finalize it.
    * See [`fbxcel::writer::v7400::binary`](https://docs.rs/fbxcel/0.9.0/fbxcel/writer/v7400/binary/index.html).

## Streaming style

1. Open the FBX file by [`fbxcel::pull_parser::any::AnyParser`](https://docs.rs/fbxcel/0.9.0/fbxcel/pull_parser/index.html)
    * See [`fbxcel::pull_parser`](https://docs.rs/fbxcel/0.9.0/fbxcel/pull_parser/index.html).
2. Open the output file and pass it to [`fbxcel::writer::v7400::binary::Writer::new()`](https://docs.rs/fbxcel/0.9.0/fbxcel/writer/v7400/binary/struct.Writer.html#method.new)
2. Read node events by [`fbxcel::pull_parser::v7400::Parser::next_event()`](https://docs.rs/fbxcel/0.9.0/fbxcel/pull_parser/v7400/struct.Parser.html#method.next_event).
3. For each node events, check whether it is the node you want to change, and write through [`fbxcel::writer::v7400::binary::Writer`](https://docs.rs/fbxcel/0.9.0/fbxcel/writer/v7400/binary/struct.Writer.html).
    * To modify attribute values, simply write the modified attribute value instead of the read one.
4. Once all events are read from the parser, finalize the writer.

**Comment by lucasjinreal** [comment]
@lo48576 hi, I finally able to loop the fbx binary in fbxel.

I used the streaming way like this:

```rust
fn load_fbx_binary_v7400<R: std::io::Read>(
    mut parser: fbxbin::v7400::Parser<R>,
    // node_tree: &FbxNodeTree,
    // node_attrs: &FbxAttributeTable,
) -> fbxbin::Result<()> {
    // let mut open_nodes_iter = Vec::new();
    let mut attr_index = 0;

    'load_nodes: loop {
        use fbxbin::v7400::*;

        match parser.next_event()? {
            Event::StartNode(node) => {
                let name = node.name().to_owned();
                let mut attributes = node.attributes();
                // let tree_iter = node_tree.append(
                //     open_nodes_iter.last(),
                //     &name,
                //     attributes.total_count(),
                //     attr_index,
                // );

                println!("name: {}, attris: {}", name, attributes.total_count());
                attr_index += attributes.total_count();
                // open_nodes_iter.push(tree_iter);
                while let Some(attr) = attributes.load_next(AttributeLoader)? {
                    // node_attrs.push_attribute(attr);
                }
            }
            Event::EndNode => {
                // open_nodes_iter.pop();
            }
            Event::EndFbx(footer_res) => {
                // node_tree.append(None, "(FBX footer)", None, 0);
                let _ = footer_res?;
                break 'load_nodes;
            }
        }
    }

    Ok(())
}
```

Token from your nice example. but now I got a problem.

For a FBX which normally contains a human's skeleton, I don't know how to get the skeleton exactly.

The tree looped just like this:

```
name: P, attris: 5
name: MultiLayer, attris: 1
name: MultiTake, attris: 1
name: Shading, attris: 1
name: Culling, attris: 1
name: NodeAttribute, attris: 3
name: TypeFlags, attris: 1
name: Properties70, attris: 0
name: P, attris: 5
name: Model, attris: 3
name: Version, attris: 1
name: Properties70, attris: 0
name: P, attris: 7
name: P, attris: 5
name: P, attris: 5
name: MultiLayer, attris: 1
name: MultiTake, attris: 1
name: Shading, attris: 1
name: Culling, attris: 1
name: NodeAttribute, attris: 3
name: TypeFlags, attris: 1
name: Properties70, attris: 0
name: P, attris: 5
name: Model, attris: 3
name: Version, attris: 1
name: Properties70, attris: 0
name: P, attris: 7
name: P, attris: 5
name: P, attris: 5
name: MultiLayer, attris: 1
name: MultiTake, attris: 1
name: Shading, attris: 1
name: Culling, attris: 1
name: NodeAttribute, attris: 3
name: TypeFlags, attris: 1
name: Properties70, attris: 0
name: P, attris: 5
name: Model, attris: 3
name: Version, attris: 1
name: Properties70, attris: 0
name: P, attris: 7
name: P, attris: 5
name: P, attris: 5
name: MultiLayer, attris: 1
name: MultiTake, attris: 1
name: Shading, attris: 1
name: Culling, attris: 1
name: NodeAttribute, attris: 3
name: TypeFlags, attris: 1
name: Properties70, attris: 0
name: P, attris: 5
name: Model, attris: 3
name: Version, attris: 1
name: Properties70, attris: 0
name: P, attris: 7
name: P, attris: 5
name: P, attris: 5
name: MultiLayer, attris: 1
name: MultiTake, attris: 1
name: Shading, attris: 1
name: Culling, attris: 1
name: NodeAttribute, attris: 3
name: TypeFlags, attris: 1
name: Properties70, attris: 0
name: P, attris: 5
name: Model, attris: 3
name: Version, attris: 1
name: Properties70, attris: 0
name: P, attris: 7
name: P, attris: 5
name: P, attris: 5
name: MultiLayer, attris: 1
name: MultiTake, attris: 1
name: Shading, attris: 1
name: Culling, attris: 1
name: NodeAttribute, attris: 3
name: TypeFlags, attris: 1
name: Properties70, attris: 0
name: P, attris: 5
name: Model, attris: 3
name: Version, attris: 1
name: Properties70, attris: 0
name: P, attris: 7
name: P, attris: 5
name: P, attris: 5
name: MultiLayer, attris: 1
name: MultiTake, attris: 1
name: Shading, attris: 1
name: Culling, attris: 1
name: NodeAttribute, attris: 3
name: TypeFlags, attris: 1
name: Properties70, attris: 0
name: P, attris: 5
name: Model, attris: 3
```

So, how to get the skeletron names I want and then change it's names properly?

**Comment by lo48576** [comment]
Maybe the names are stored as attributes, and skeleton may be represented by (some subset of) `Model` nodes.

See <https://github.com/lo48576/fbx_objects_depviz/blob/master/examples/models.dot.svg>.

![](https://raw.githubusercontent.com/lo48576/fbx_objects_depviz/master/examples/models.dot.svg)

`Model` object node that represents skeleton has three attrs: object ID in integer, `{object_name}\x00\x01Model` in string, and the string `LimbNode`, in order.
I'm not 100% sure but maybe changing the string before \x00\x01 would be what you wanted to do.

Remember checking the last attribute value before modification: `Model` nodes are also used to represent objects other than skeleton.

**Comment by lucasjinreal** [comment]
@lo48576  thank u. I only saw there are 3 attri in every LimbNode, which is what I need the skeleton bone names.

However, these 3 attris are simply id, name, LimbNode, how can I identify if it actually a Limb Name?
and How can I get the connection between?

Also, why there is a \x00\x01Model string after the name?

**Comment by lo48576** [comment]
> However, these 3 attris are simply id, name, LimbNode, how can I identify if it actually a Limb Name?

What do you mean?
If the node name is `Model`, the second attribute ends with `\x00\x01Model`, and the third attribute is `LimbName`, then it would actually be a limb node (at least I believe so).
If the node name is not `Model` or third attribute is not `LimbNode`, then it is something else...

Note that such nodes (non-limb node?) may exist in limb nodes hierarchy.
I don't know what it actually mean and how to handle it, but it might be something like dummy nodes?
![2023-01-21-120110+0900](https://user-images.githubusercontent.com/1246590/213840881-4885583c-1f86-4af9-8352-d295c28416e7.png)

> and How can I get the connection between?

You should use info from toplevel `Connections` node and the children `C` nodes.
The resources below may help you understand representation of object hierarchies.

* [User:Mont29/Foundation/FBX File Structure - BlenderWiki](https://archive.blender.org/wiki/index.php/User:Mont29/Foundation/FBX_File_Structure/)
* [Autodesk FBX SDK Progammer's Guide: Connections](https://download.autodesk.com/us/fbx/20112/fbx_sdk_help/index.html?url=WS73099cc142f487551fea285e1221e4f9ff8-7fda.htm,topicNumber=d0e6388)
* [FBX Connections · Issue #1809 · assimp/assimp · GitHub](https://github.com/assimp/assimp/issues/1809)

![2023-01-21-121427+0900](https://user-images.githubusercontent.com/1246590/213841259-bb174088-21a2-4205-b8db-15b4bbf7112a.png)

> Also, why there is a \x00\x01Model string after the name?

Ask to people in Autodesk :-)
As far as I know, it is not always same as the node name. For example, there would be nodes named `Deformer`, with the second attribute `\x00\x01SubDeformer`, and the third attribute `Cluster`.
However, it would be safe to ignore that prefix for `Model` nodes (of course there are no guarantees since the FBX is proprietary closed format).

**Comment by lucasjinreal** [comment]
thank u.  I saw that fbxel_dom seems parsed Model, Scene, Camera already, which part (or API) can I use directly if I want using it parse skeleton simply (no animation)?

I just need LimbNode names and it's connections (for display) and the names for modification.

**Comment by lo48576** [comment]
Limb nodes can be accessible as [`fbxcel_dom::v7400::object::model::LimbNodeHandle`](https://docs.rs/fbxcel-dom/latest/fbxcel_dom/v7400/object/model/struct.LimbNodeHandle.html), and you can get node names by [`name()`](https://docs.rs/fbxcel-dom/latest/fbxcel_dom/v7400/object/model/struct.LimbNodeHandle.html#method.name) method.
The type does not have any methods specific to limb node, but it would be enough to traverse objects hierarchy and getting object ID and names.
Note that fbxcel\_dom currently does not support modification, so you cannot edit FBX data through fbxcel\_dom.

**Comment by lucasjinreal** [comment]
@lo48576 hi as you said earliier, using [fbxcel::writer::v7400::binary::Writer](https://docs.rs/fbxcel/0.9.0/fbxcel/writer/v7400/binary/struct.Writer.html) to write, I might canusing fbxcel_dom to get node id, which I needed, then using Writer to write,
can u teach me how to combine them to modify and save it?

**Comment by lo48576** [comment]
I don't know precisely what you wanted to do, so this would neither optimal nor simplest way, but this will basically work.

1. Load the tree with fbxcel\_dom and remember the tree you are interested in. Especially, object ID, object type, and some attributes for each object node, and parent-child (or "source-destination" in FBX term) relationships of object nodes.
2. Now you know nodes to edit and how they make a tree. Read the nodes by fbxcel, edit nodes that matches the condition, and pass them to the writer.

**Comment by lo48576** [comment]
Feel free to reopen if this still matters.
